application: happyfoot-cl
runtime: nodejs
env: flex
threadsafe: true
automatic_scaling:
  min_num_instances: 2
  max_num_instances: 10
  cpu_utilization:
    target_utilization: 0.8
resources:
  cpu: 2
  memory_gb: 2.3
